# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-06 19:51
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Alertas',
            fields=[
                ('Numero_alertas', models.AutoField(primary_key=True, serialize=False)),
                ('Tipo', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Estacionamiento',
            fields=[
                ('rif', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True, verbose_name='rif')),
                ('nombre', models.CharField(max_length=200)),
                ('numero_de_puestos', models.IntegerField(default=1000)),
                ('acceso_restringido', models.BooleanField(default=True)),
                ('email', models.EmailField(max_length=255, verbose_name='email address')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Ocurre_a',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fecha_alertas', models.DateTimeField(verbose_name='fecha de alerta')),
            ],
        ),
        migrations.CreateModel(
            name='Ocurre_en',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fecha_alertas', models.DateTimeField(verbose_name='fecha de alerta')),
                ('Numero_alertas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ac_seguridad.Alertas')),
                ('RIF', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ac_seguridad.Estacionamiento')),
            ],
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('nombre', models.CharField(max_length=20)),
                ('apellido', models.CharField(max_length=25)),
                ('cedula', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True, verbose_name='cedula')),
                ('telefono', models.CharField(max_length=25)),
                ('email', models.EmailField(max_length=255, verbose_name='email address')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Numero_ticket', models.IntegerField(default=0)),
                ('Hora_entrada', models.DateTimeField(verbose_name='Hora de entrada')),
                ('Hora_salida', models.DateTimeField(verbose_name='Hora de salida')),
                ('Pagado', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Vehiculos',
            fields=[
                ('Placa', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('Cedula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ac_seguridad.Persona')),
            ],
        ),
        migrations.AddField(
            model_name='ticket',
            name='Placa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ac_seguridad.Vehiculos'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='RIF',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ac_seguridad.Estacionamiento'),
        ),
        migrations.AddField(
            model_name='ocurre_a',
            name='Cedula_usuarios_en_alertas',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ac_seguridad.Persona'),
        ),
        migrations.AddField(
            model_name='ocurre_a',
            name='Numero_alertas',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ac_seguridad.Alertas'),
        ),
    ]
