# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-08 19:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ac_seguridad', '0003_auto_20170808_1410'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='Hora_entrada',
            new_name='hora_entrada',
        ),
        migrations.RenameField(
            model_name='ticket',
            old_name='Hora_salida',
            new_name='hora_salida',
        ),
        migrations.RenameField(
            model_name='ticket',
            old_name='Numero_ticket',
            new_name='numero_ticket',
        ),
        migrations.RenameField(
            model_name='ticket',
            old_name='Pagado',
            new_name='pagado',
        ),
        migrations.RenameField(
            model_name='ticket',
            old_name='Placa',
            new_name='placa',
        ),
        migrations.RenameField(
            model_name='ticket',
            old_name='RIF',
            new_name='rif',
        ),
    ]
