# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-14 20:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ac_seguridad', '0004_auto_20170808_1926'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alerta',
            old_name='Numero_alertas',
            new_name='numero_alertas',
        ),
        migrations.RenameField(
            model_name='alerta',
            old_name='Tipo',
            new_name='tipo',
        ),
        migrations.RenameField(
            model_name='ocurre_a',
            old_name='Cedula_usuarios_en_alertas',
            new_name='cedula_usuarios_en_alertas',
        ),
        migrations.RenameField(
            model_name='ocurre_a',
            old_name='Fecha_alertas',
            new_name='fecha_alertas',
        ),
        migrations.RenameField(
            model_name='ocurre_a',
            old_name='Numero_alertas',
            new_name='numero_alertas',
        ),
        migrations.RenameField(
            model_name='ocurre_en',
            old_name='Fecha_alertas',
            new_name='fecha_alertas',
        ),
        migrations.RenameField(
            model_name='ocurre_en',
            old_name='Numero_alertas',
            new_name='numero_alertas',
        ),
        migrations.RenameField(
            model_name='ocurre_en',
            old_name='RIF',
            new_name='rif',
        ),
    ]
