# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-16 18:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ac_seguridad', '0007_auto_20170814_2255'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ocurrea',
            name='cedula_usuario',
        ),
        migrations.RemoveField(
            model_name='ocurrea',
            name='numero_alertas',
        ),
        migrations.RemoveField(
            model_name='ocurreen',
            name='numero_alertas',
        ),
        migrations.RemoveField(
            model_name='ocurreen',
            name='rif',
        ),
        migrations.AddField(
            model_name='alerta',
            name='estacionamiento',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ac_seguridad.Estacionamiento'),
        ),
        migrations.AddField(
            model_name='alerta',
            name='fecha',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='fecha de alerta'),
        ),
        migrations.AddField(
            model_name='alerta',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ac_seguridad.Persona'),
        ),
        migrations.AddField(
            model_name='alerta',
            name='vehiculo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ac_seguridad.Vehiculo'),
        ),
        migrations.DeleteModel(
            name='OcurreA',
        ),
        migrations.DeleteModel(
            name='OcurreEn',
        ),
    ]
