# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-16 18:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ac_seguridad', '0008_auto_20170816_1801'),
    ]

    operations = [
        migrations.AddField(
            model_name='alerta',
            name='ticket',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ac_seguridad.Ticket'),
        ),
    ]
