# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-16 18:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ac_seguridad', '0009_alerta_ticket'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alerta',
            name='ticket',
        ),
    ]
