# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-29 22:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ac_seguridad', '0010_remove_alerta_ticket'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketNoResgistrado',
            fields=[
                ('placa', models.CharField(max_length=25)),
                ('numero_ticket', models.AutoField(primary_key=True, serialize=False)),
                ('hora_entrada', models.DateTimeField(verbose_name='Hora de entrada')),
                ('hora_salida', models.DateTimeField(verbose_name='Hora de salida')),
                ('pagado', models.BooleanField(default=False)),
                ('rif', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ac_seguridad.Estacionamiento')),
            ],
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='id',
        ),
        migrations.AlterField(
            model_name='ticket',
            name='numero_ticket',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
