# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-29 22:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ac_seguridad', '0011_auto_20170929_2254'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TicketNoResgistrado',
            new_name='TicketNoRegistrado',
        ),
    ]
