# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-29 23:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ac_seguridad', '0012_auto_20170929_2255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='hora_salida',
            field=models.DateTimeField(null=True, verbose_name='Hora de salida'),
        ),
        migrations.AlterField(
            model_name='ticketnoregistrado',
            name='hora_salida',
            field=models.DateTimeField(null=True, verbose_name='Hora de salida'),
        ),
    ]
