# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-30 22:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ac_seguridad', '0013_auto_20170929_2346'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('numero_actividad', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=200)),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now, verbose_name='fecha de actividad')),
                ('estacionamiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ac_seguridad.Estacionamiento')),
                ('ticket', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ac_seguridad.Ticket')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ac_seguridad.Persona')),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ac_seguridad.Vehiculo')),
            ],
        ),
    ]
