# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-01 17:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ac_seguridad', '0014_actividad'),
    ]

    operations = [
        migrations.AddField(
            model_name='estacionamiento',
            name='monto_tarifa',
            field=models.IntegerField(default=1000),
        ),
        migrations.AddField(
            model_name='estacionamiento',
            name='tarifa_plana',
            field=models.BooleanField(default=True),
        ),
    ]
