# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-18 00:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ac_seguridad', '0016_auto_20171001_1738'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='enviar_correo',
            field=models.BooleanField(default=True),
        ),
    ]
