# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-19 22:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ac_seguridad', '0018_auto_20171019_2228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alerta',
            name='usuario',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
